#!/usr/bin/bash

main() {
    if [[ -n "$1" ]]; then
	exec setsid uwsm app -- chromium \
	    --profile-directory=Webapp \
	    --app="$1" \
	    "${@:2}"
    else
	echo "No webapp url given"
    fi
}

main "$@"
