# Variable to use when integrating Hyprland into a Shell
# Leave empty to unset
# $ipc = ""				    # no shell integration
$ipc = qs -c noctalia-shell ipc call	    # noctalia-shell

# Noctalia Core Binds
bindd = SUPER, SPACE,	Open Launcher,			exec, $ipc launcher toggle
bindd = SUPER, period,	Open Control Center,		exec, $ipc controlCenter toggle
bindd = SUPER, comma,	Open Noctalia Settings,		exec, $ipc settings toggle
bindd = SUPER SHIFT, S, Screenshot selected region,	exec, $ipc plugin:screen-shot-and-record screenshot
bindd = SUPER SHIFT, T, OCR selected region,		exec, $ipc plugin:screen-shot-and-record ocr
