# Alias
source .config/alias/alias

# Sourcing
source .config/zsh/sources/environment
source .config/zsh/sources/bindings

# Starship
eval "$(starship init zsh)"

# Zoxide
eval "$(zoxide init zsh)"

# Mise
eval "$(mise activate zsh)"
