#!/bin/bash
set -e

dotdir="$HOME/.dotfiles"
default_shell="/bin/zsh"

_keepalive() {
    # Forces password prompt
    sudo -v

    # Run a loop in the background that refreshed sudo every 30 seconds
    # to avoid the permission expiring in the middle of the instalation
    (while true; do sudo -n true; sleep 30; kill -0 "$$" || exit; done) &

    # We get the PID of the loop we just started
    local keepalive_pid=$!

    # Traps and kill the look as soon as the main script is finished to
    # avoid having it running when it shouldn't
    trap "kill $keepalive_pid 2>/dev/null" EXIT
}

_header() {
    local title="$1"

    echo "===> $title"
    echo ""
}

_run_task() {
    local title="$1"
    shift

    echo "===> $title"
    "$@"
    echo "===> Done."
    echo ""
}

_config_mounts() {
    local unitName="run-media-israel-EMDRIVE.mount"
    local mountUnitPath="$dotdir/src/applications/systemd/system/$unitName"
    local targetDir="/etc/systemd/system"

    sudo install -m 644 "$mountUnitPath" "$targetDir/$unitName"
}

_config_deluged() {
    local targetdir="/etc/systemd/system/deluged.service.d"
    sudo mkdir -p "$targetdir"
    sudo install -m 644 "$dotdir/src/applications/deluge/override.conf" "$targetdir/override.conf"
}

_restart_daemons() {
    sudo systemctl daemon-reload
}

_enable_units() {
    sudo systemctl enable --now "run-media-israel-EMDRIVE.mount"
}

_config_systemd() {
    _header "Configuring Systemd"

    _config_mounts
    _config_deluged
    _restart_daemons

    _enable_units
}

echo "===> Dotfiles"
echo ""

_keepalive

_run_task "Updating system and installing dependencies..." \
    bash -c "
	sudo pacman -Syu --noconfirm
	sudo pacman -S --noconfirm --needed git paru
    "

_run_task "Setting up dotfiles repository..." \
    bash -c "
	if [ ! -d \"$dotdir\" ]; then
	    git clone https://github.com/israveri/dotfiles \"$dotdir\"
	    git -C \"$dotdir\" remote set-url origin git@github.com:israveri/dotfiles.git
	    git -C \"$dotdir\" remote rename origin github
	fi
    "

_run_task "Setting up git submodules..." \
    git -C "$dotdir" submodule update --init

_run_task "Installing packages from packages.txt manifest..." \
    paru -S --noconfirm --needed - < "$dotdir/src/packages/manifest.txt"

_run_task "Installing Screenshot utility" \
    bash -c "
	if [ ! -d \"$HOME/Workspace/humbleshot\" ]; then
	    mkdir -p \"$HOME/Workspace/\"
	    git clone https://github.com/israveri/humbleshot \"$HOME/Workspace/humbleshot\"
	    git -C \"$HOME/Workspace/humbleshot\" remote set-url origin git@github.com:israveri/humbleshot.git
	    git -C \"$HOME/Workspace/humbleshot\" remote rename origin github
	else
	    echo \"Repo already exists. Skipping.\"
	fi
	ln -sf \"$HOME/Workspace/humbleshot/humbleshot\" \"$dotdir/stow/usr-scripts/dot-local/scripts/humbleshot\"
    "

_run_task "Stowing dotfiles..." \
    bash -c "
	rm "$HOME/.zshrc"
	cd "$dotdir/stow" && stow --dotfiles --dir="$dotdir/stow" --target="$HOME" -v1 */
    "

_run_task "Setting up SDDM..." \
    bash -c "
	sudo mkdir -p /etc/sddm.conf.d
	sudo ln -sf "$dotdir/src/applications/sddm/custom.conf" /etc/sddm.conf.d/custom.conf
	setfacl -m u:sddm:x "$HOME"
	setfacl -m u:sddm:r "$HOME/.face.icon"
	sudo cp "$dotdir/src/applications/sddm/hyprland*" /usr/share/wayland-sessions/
    "

_run_task "Setting up Zsh..." \
    sudo chsh -s "$default_shell" $(whoami)

_run_task "Setting up Neovim plugins..." \
    nvim --headless "+Lazy! sync" +qa

_run_task "Installing programming languages..." \
    mise install

_run_task "Enabling service units..." \
    sudo systemctl enable $(cat "$dotdir/src/services/manifest.txt")

_setup_deluged
_restart_daemons

_run_task "Reloading Hyprland" \
    hyprctl reload

echo ""
echo "✅ Installation complete"
