#!/bin/bash
set -e

dotdir="$HOME/.dotfiles"
defaultShell="/bin/zsh"

_header() {
    local title="$1"

    echo ""
    echo ""
    echo "===== $title ===================="
}

_keepalive() {
    # Forces password prompt
    sudo -v

    # Run a loop in the background that refreshed sudo every 30 seconds
    # to avoid the permission expiring in the middle of the instalation
    (while true; do sudo -n true; sleep 30; kill -0 "$$" || exit; done) &

    # We get the PID of the loop we just started
    local keepalive_pid=$!

    # Traps and kill the look as soon as the main script is finished to
    # avoid having it running when it shouldn't
    trap "kill $keepalive_pid 2>/dev/null" EXIT
}

_prepare() {
    _header "Dotfiles"
    _keepalive
}

_resolve_dependencies() {
    _header "Installing dependencies"

    sudo pacman -Syu --noconfirm
    sudo pacman -S --noconfirm --needed git paru
}

_clone_self() {
    _header "Cloning dotfiles repository"

    local repoHttps="https://github.com/israveri/dotfiles"
    local repoGit="git@github.com:israveri/dotfiles.git"

    if [ ! -d "$dotdir" ]; then
        git clone "$repoHttps" "$dotdir"
        git -C "$dotdir" remote set-url origin $repoGit
        git -C "$dotdir" remote rename origin github
    fi
}

_install_git_submodules() {
    _header "Installing git submodules"

    git -C "$dotdir" submodule update --init
}

_install_packages() {
    local manifestPath="$dotdir/src/packages/manifest.txt"

    _header "Installing packages from manifest"

    paru -S --noconfirm --needed - < "$manifestPath"
}

_install_humbleshot() {
    local targetDir="$HOME/Workspace/humbleshot"

    _header "Installing screenshot tool"

    if [ ! -d "$targetDir" ]; then
        mkdir -p "$HOME/Workspace/"
        git clone "https://github.com/israveri/humbleshot" "$targetDir"
        git -C "$targetDir" remote set-url origin "git@github.com:israveri/humbleshot"
        git -C "$targetDir" remote rename origin github
    else
        echo "Repo already exists. Skipping."
    fi

    ln -sf "$targetDir/humbleshot" "$dotdir/stow/usr-scripts/dot-local/scripts/humbleshot"
}

_install_dotfiles() {
    _header "Stowing dotfiles"

    [ -f "$HOME/.zshrc" ] && rm "$HOME/.zshrc"
    cd "$dotdir/stow" && stow --dotfiles --dir="$dotdir/stow" --target="$HOME" -v1 */
}

_customize_sddm() {
    _header "Customizing SDDM"

    sudo mkdir -p "/etc/sddm.conf.d"

    sudo install -m 644 "$dotdir/src/applications/sddm/custom.conf" "/etc/sddm.conf.d/custom.conf"
    sudo install -m 644 "$dotdir/src/applications/sddm/hyprland.desktop" "/usr/share/wayland-sessions/hyprland.desktop"
    sudo install -m 644 "$dotdir/src/applications/sddm/hyprland-uwsm.desktop" "/usr/share/wayland-sessions/hyprland-uwsm.desktop"

    setfacl -m u:sddm:x "$HOME"
    setfacl -m u:sddm:r "$HOME/.face.icon"
}

_change_default_shell() {
    _header "Changing default shell"

    sudo chsh -s "$defaultShell" "$(whoami)"
}

_install_neovim_plugins() {
    _header "Installing Neovim plugins"

    nvim --headless "+Lazy! sync" +qa
}

_install_devenv() {
    _header "Installing dev env"

    mise install
}

_enable_systemd_units() {
    _header "Enabling service units"
    sudo systemctl enable $(cat "$dotdir/src/services/manifest.txt")
}

_config_mounts() {
    local unitName="run-media-israel-EMDRIVE.mount"
    local mountUnitPath="$dotdir/src/applications/systemd/system/$unitName"
    local targetDir="/etc/systemd/system"

    sudo install -m 644 "$mountUnitPath" "$targetDir/$unitName"
}

_config_deluged() {
    local sourcedir="$dotdir/src/applications/systemd/deluged.service.d"
    local targetdir="/etc/systemd/system/deluged.service.d"
    sudo mkdir -p "$targetdir"
    sudo install -m 644 "$sourcedir/override.conf" "$targetdir/override.conf"
}

_restart_daemons() {
    sudo systemctl daemon-reload
}

_enable_mount_units() {
    sudo systemctl enable --now "run-media-israel-EMDRIVE.mount"
}

_customize_systemd_units() {
    _header "Configuring Systemd"

    _config_mounts
    _config_deluged
    _restart_daemons

    _enable_mount_units
}

_reload_hyprland() {
    _header "Restarting Hyprland"

    if [ -n "$HYPRLAND_INSTANCE_SIGNATURE" ]; then
        hyprctl reload
    else
        echo "Hyprland not running. Skipping."
    fi

}

_finish() {
    echo ""
    echo "✅ Installation complete"
}

_main() {
    # Preparation phase
    _prepare
    _resolve_dependencies
    _clone_self 
    _install_git_submodules

    # Main installations
    _install_packages 
    _install_humbleshot
    _install_dotfiles
    _install_neovim_plugins
    _install_devenv

    # Programs customizations and adjustments
    _customize_sddm
    _change_default_shell
    _enable_systemd_units
    _customize_systemd_units

    # Cleanup
    _reload_hyprland
    _finish
}

_main
