#!/usr/bin/env bash
# Auto-generated by Noctalia — do not edit directly
# Applies current-mode VT palette via console ESC]Pn escape codes.
# Usage: vt-palette.sh [/dev/ttyN]

TARGET="${1:-/dev/tty1}"

{
printf "\e]P0{{colors.terminal_normal_black.default.hex_stripped}}"
printf "\e]P1{{colors.terminal_normal_red.default.hex_stripped}}"
printf "\e]P2{{colors.terminal_normal_green.default.hex_stripped}}"
printf "\e]P3{{colors.terminal_normal_yellow.default.hex_stripped}}"
printf "\e]P4{{colors.terminal_normal_blue.default.hex_stripped}}"
printf "\e]P5{{colors.terminal_normal_magenta.default.hex_stripped}}"
printf "\e]P6{{colors.terminal_normal_cyan.default.hex_stripped}}"
printf "\e]P7{{colors.terminal_normal_white.default.hex_stripped}}"
printf "\e]P8{{colors.terminal_bright_black.default.hex_stripped}}"
printf "\e]P9{{colors.terminal_bright_red.default.hex_stripped}}"
printf "\e]PA{{colors.terminal_bright_green.default.hex_stripped}}"
printf "\e]PB{{colors.terminal_bright_yellow.default.hex_stripped}}"
printf "\e]PC{{colors.terminal_bright_blue.default.hex_stripped}}"
printf "\e]PD{{colors.terminal_bright_magenta.default.hex_stripped}}"
printf "\e]PE{{colors.terminal_bright_cyan.default.hex_stripped}}"
printf "\e]PF{{colors.terminal_bright_white.default.hex_stripped}}"
} > "$TARGET"
