# Allows Picture-in-Picture to float
windowrule {
  name = firefox-pip
  match:title = ^(Picture-in-Picture)$

  float = on
  pin = on
  size = 512 288 # 800 450 | 512 288 | 400 225
  move = ((monitor_w*1)-532) ((monitor_h*1)-308) # 820 470 | 532 308 | 420 245
}

