# Allows Picture-in-Picture to float, pins it to the screen and removes any opacity from inactivity
windowrule {
  name = firefox-pip
  match:title = ^(Picture-in-Picture)$

  float = on
  pin = on
  opacity = 1.0 1.0 override
  size = 512 288 # 800 450 | 512 288 | 400 225
  move = ((monitor_w*1)-532) ((monitor_h*1)-308) # 820 470 | 532 308 | 420 245
}

