windowrule {
  name = mission-center-float
  match:title = ^(Mission Center)$

  float = on
  pin = on
  opacity = 1.0 1.0 override
  center = on
  size = 1789 1006 # 1600x900 * 1.25 scaling factor
}
