[config]

[templates]
[templates.cheatsheet]
input_path = "~/.config/noctalia/templates/noctalia-colorscheme-cheatsheet-template.txt"
output_path = "~/.dotfiles/noctalia-colorscheme-cheatsheet.txt"

[templates.nvim-base16]
input_path = "~/.config/noctalia/templates/nvim-template.lua"
output_path = "~/.config/nvim/lua/colors/noctalia.lua"
post_hook = 'pkill -SIGUSR1 nvim'
