[general]
import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[window]
decorations = "None"
padding = { x = 10, y = 10 }

[font]
normal = { family = "CaskaydiaMono Nerd Font Mono", style = "Regular" }
size = 11

[cursor]
style = { shape = "Block", blinking = "Off" }
