alias ...="cd ../.."
alias ..="cd .."
alias cat="bat"
alias grep="grep --color=always"
alias ls="eza --header --long --git --classify --group-directories-first --color=always"
alias lsa="ls --all"
alias lt="ls --tree -L1 --icons --no-permissions --no-filesize --no-user --no-time --no-git"
alias lta="lt --all"
