# See https://wiki.hypr.land/Configuring/Keywords/

source = ~/.config/hypr/bindings/integration.conf
source = ~/.config/hypr/bindings/core.conf
source = ~/.config/hypr/bindings/tiling.conf
source = ~/.config/hypr/bindings/media.conf

