# See https://wiki.hypr.land/Configuring/Keywords/

# Variable to use when integrating Hyprland into a Shell
# Leave empty to unset
# $ipc = ""				    # no shell integration
$ipc = qs -c noctalia-shell ipc call	    # noctalia-shell

source = ~/.config/hypr/bindings/tiling.conf
source = ~/.config/hypr/bindings/media.conf

# Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
bindd = SUPER, RETURN,  Open Terminal,			exec, uwsm app -- $terminal
bindd = SUPER, B,       Open Browser,			exec, uwsm app -- $browser
bindd = SUPER, Q,       Closes active window,		killactive
bindd = SUPER, M,       Closes Hyprland,		exit
bindd = SUPER, E,       Open File Explorer,		exec, uwsm app -- $fileManager
bindd = SUPER, V,       Toggle float on active window,	togglefloating
bindd = SUPER, Z,       Maximizes active window,	fullscreen, 1

# Noctalia Core Binds
bindd = SUPER, SPACE,	Open Launcher,			exec, $ipc launcher toggle
bindd = SUPER, period,	Open Control Center,		exec, $ipc controlCenter toggle
bindd = SUPER, comma,	Open Noctalia Settings,		exec, $ipc settings toggle
bindd = SUPER SHIFT, S, Screenshot selected region,	exec, $ipc plugin:screen-shot-and-record screenshot
bindd = SUPER SHIFT, T, OCR selected region,		exec, $ipc plugin:screen-shot-and-record ocr

# Screenshot
#bindd = SUPER, PRINT,   Take screenshot,                      exec, hyprshot -m output -m active -f "Screenshots/$(date +%F_%T).png"
#bindd = SUPER SHIFT, S, Take screenshot of selected region,   exec, hyprshot -m region -f "Screenshots/$(date +%F_%T).png"
