source = ~/.config/hypr/applications/firefox.conf
source = ~/.config/hypr/applications/pqiv.conf
source = ~/.config/hypr/applications/steam.conf
source = ~/.config/hypr/applications/gnome-calculator.conf

# Prevent Hyprland from messing with the Gamescope initial surface
windowrule {
  name = gamescope
  immediate = on
  fullscreen = on
  monitor = 0
  match:class = ^(gamescope)$
}

