alias ga="git add"
alias gb="git branch"
alias gc="git commit"
alias gco="git checkout"
alias gd="git diff"
alias gds="git diff --staged"
alias glog="git log --graph --oneline -n 5"
alias gst="git status"
