autoload -U compinit && compinit

[[ -f "$XDG_CONFIG_HOME/zsh/shell/core.zsh" ]] && source "$XDG_CONFIG_HOME/zsh/shell/core.zsh"

# fzf
source <(fzf --zsh)
source /usr/share/fzf/completion.zsh
source /usr/share/fzf/key-bindings.zsh

# Starship
eval "$(starship init zsh)"

# Zoxide
eval "$(zoxide init zsh)"

# Mise
eval "$(mise activate zsh)"
