# For all options see https://sw.kovidgoyal.net/kitty/conf/

# Background
background_opacity 1.0

# Fonts
font_family family="IntoneMono Nerd Font"
font_size 12

# Window Layout
window_padding_width 0 10

# Scrolling
scrollback_lines 10000


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
