# For all options see https://sw.kovidgoyal.net/kitty/conf/

# Fonts
font_family	family="IntoneMono Nerd Font"
font_size	12

# Window Layout
window_padding_width	10 10


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
