# For all options see https://sw.kovidgoyal.net/kitty/conf/

# Background
background_opacity 1.0

# Fonts
font_family family="IntoneMono Nerd Font"
font_size 14

# Cursor
cursor_trail 10
cursor_trail_start_threshold 0
cursor_trail_decay 0.01 0.1
cursor_shape block
cursor_blink true

# Window Layout
window_padding_width 0 10

# Scrolling
scrollback_lines 10000

# Fixes for modified key mappings that Kitty just swallows or
# sends different keystrokes to applications (e.g. neovim)
map ctrl+tab send_text all \x1b[9;5u
map ctrl+shift+tab send_text all \x1b[9;6u
map ctrl+enter send_text all \x1b[13;5u
map shift+enter send_text all \x1b[13;2u
map ctrl+backspace send_text all \x1b[127;5u
map ctrl+, send_text all \x1b[44;5u
map ctrl+. send_text all \x1b[46;5u
map ctrl+/ send_text all \x1b[47;5u

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
