# Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
bindd = SUPER, RETURN,  Open Terminal,                  exec, uwsm app -- $terminal
bindd = SUPER, B,       Open Browser,                   exec, uwsm app -- $browser
bindd = SUPER, Q,       Closes active window,           killactive
bindd = SUPER, M,       Closes Hyprland,                exit
bindd = SUPER, E,       Open File Explorer,             exec, uwsm app -- $fileManager
bindd = SUPER, V,       Toggle float on active window,  togglefloating
bindd = SUPER, Z,       Maximizes active window,        fullscreen, 1


# Screenshot
bindd = SUPER, F12,     Take screenshot,                      exec, humbleshot screen
bindd = SUPER SHIFT, S, Take screenshot of selected region,   exec, humbleshot
