# Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
bindd = SUPER, RETURN,  Open Terminal,                  exec, uwsm app -- $terminal
bindd = SUPER, B,       Open Browser,                   exec, uwsm app -- $browser
bindd = SUPER, Q,       Closes active window,           killactive
bindd = SUPER, M,       Closes Hyprland,                exit
bindd = SUPER, E,       Open File Explorer,             exec, uwsm app -- $fileManager
bindd = SUPER, Tab,     Overview,                       exec, qs ipc -c overview call overview toggle

# Screenshot
bindd = SUPER, F12,     Take screenshot,                      exec, uwsm app -- humbleshot screen
bindd = SUPER SHIFT, S, Take screenshot of selected region,   exec, uwsm app -- humbleshot

# Mission Center
bindd = SUPER SHIFT, ESCAPE, Opens Mission Center, exec, uwsm app -- missioncenter
