# Variable to use when integrating Hyprland into a Shell
# Leave empty to unset
# $ipc = ""				    # no shell integration
$ipc = qs -c noctalia-shell ipc call	    # noctalia-shell

# Noctalia Core Binds
bindd = SUPER, SPACE,   Open Launcher,                  exec, $ipc launcher toggle
bindd = SUPER, period,  Open Control Center,            exec, $ipc controlCenter toggle
bindd = SUPER, L,       Lock Session,                   exec, $ipc lockScreen lock
bindd = SUPER, comma,   Open Noctalia Settings,         exec, $ipc settings toggle
bindd = SUPER, A,	Open AI assistant,		exec, qs -c noctalia-shell ipc call plugin:assistant-panel toggle
