[botdetection]
ipv4_prefix = 32
ipv6_prefix = 48

trusted_proxies = [
  '127.0.0.0/8',
  '::1',
  '192.168.0.0/16',
  '10.88.0.0/16',           # podman
  '10.89.0.0/16',           # search
  '10.100.0.0/16',          # homelab
]

[botdetection.ip_limit]
link_token = false
