use_default_settings: true

general:
  instance_name: "Mothership Search"
  debug: false

server:
  bind_address: "0.0.0.0"
  port: 8080
  method: "GET"
  image_proxy: true

ui:
  default_theme: simple
  results_on_new_tab: false
  center_alignment: true

search:
  default_lang: "en-US"
  favicon_resolver: "duckduckgo"
  autocomplete: "duckduckgo"
  autocomplete_min: 3
outgoing:
  request_timeout: 5

# Which categories may appear
categories_as_tabs:
  general:
  images:
  videos:
  news:
  map:
  it:
  science:
  files:

  plugins:
    searx.plugins.oa_doi_rewrite.SXNGPlugin:
      active: true

# Which search engines are enabled/disabled
engines:
  # General engines
  - name: aol
    disabled: true
  - name: bing
    disabled: true
  - name: brave
    disabled: true
  - name: duckduckgo
    disabled: false
  - name: google
    disabled: false
  - name: wikipedia
    disabled: false
  - name: karmasearch
    disabled: true
  - name: karmasearch videos
    disabled: true
  - name: startpage
    disabled: true

  # Image engines
  - name: aol images
    disabled: true
  - name: google images
    disabled: true
  - name: karmasearch images
    disabled: true
  - name: pexels
    disabled: true
  - name: qwant images
    disabled: true
  - name: startpage images
    disabled: true

  # Video engines
  - name: qwant videos
    disabled: true
  - name: vimeo
    disabled: true

  # News engines
  - name: karmasearch news
    disabled: true
  - name: qwant news
    disabled: true
  - name: startpage news
    disabled: true

  # Files engines
  - name: kickass
    disabled: true
  - name: solidtorrents
    disabled: true
