# Allows Picture-in-Picture to float
windowrule {
  name = firefox-pip
  match:title = ^(Picture-in-Picture)$

  float = on
  pin = on
  size = 800 450
  move = ((monitor_w*1)-820) ((monitor_h*1)-470)
}

