name: winboat
volumes:
  data:
services:
  windows:
    image: ghcr.io/dockur/windows:5.14
    container_name: WinBoat
    environment:
      VERSION: "11"
      RAM_SIZE: 8G
      CPU_CORES: "3"
      DISK_SIZE: 32G
      USERNAME: israel
      PASSWORD: "1234"
      HOME: ${HOME}
      LANGUAGE: English
      NETWORK: user
      USER_PORTS: "7148"
      HOST_PORTS: "7149"
      ARGUMENTS: -qmp tcp:0.0.0.0:7149,server,wait=off
    cap_add:
      - NET_ADMIN
    ports:
      - 127.0.0.1::8006
      - 127.0.0.1::7148
      - 127.0.0.1::7149
      - 127.0.0.1::3389/tcp
      - 127.0.0.1::3389/udp
    stop_grace_period: 120s
    restart: on-failure
    privileged: true
    volumes:
      - /home/israel/.local/share/winboat/:/storage
      - /home/israel/.local/share/winboat/shared:/shared
      - /home/israel/.local/share/winboat/oem:/oem
    devices:
      - /dev/kvm
      - /dev/bus/usb
